/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_flink_ml_jni_operator_VectorAddOperator */

#ifndef _Included_org_apache_flink_ml_jni_operator_VectorAddOperator
#define _Included_org_apache_flink_ml_jni_operator_VectorAddOperator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_flink_ml_jni_operator_VectorAddOperator
 * Method:    add_cpp
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_flink_ml_jni_operator_VectorAddOperator_add_1cpp
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
