/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_flink_ml_jni_core_Vector */

#ifndef _Included_org_apache_flink_ml_jni_core_Vector
#define _Included_org_apache_flink_ml_jni_core_Vector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_flink_ml_jni_core_Vector
 * Method:    toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_flink_ml_jni_core_Vector_toString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_flink_ml_jni_core_Vector
 * Method:    createNaiveObject
 * Signature: ([D)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_flink_ml_jni_core_Vector_createNaiveObject
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
